server:
  port: 8090

spring:
  application:
    name: jobda-mcp-client

  ai:
    openai:
      api-key: ${OPENAI_API_KEY_AI}
      chat:
        model: gpt-4o-mini

    mcp:
      client:
        version: 0.0.1
        enabled: true
        streamable-http:
          connections:
            jobda-server:
              url: http://10.0.100.115:8080
              endpoint: /mcp
        toolcallback:
          enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
    org.springframework.ai: DEBUG
    org.springframework.ai.chat.client.advisor: DEBUG
    org.springframework.ai.mcp: DEBUG
    org.springaicommunity.mcp: DEBUG
    org.springframework.web.client: DEBUG
    com.mcp: DEBUG