server:
  port: 8090

spring:
  application:
    name: jobda-mcp-client

  ai:
    openai:
      api-key: ${OPENAI_API_KEY_AI}
      chat:
        model: gpt-4o-mini

  autoconfigure:
    exclude:
      - org.springframework.ai.mcp.client.common.autoconfigure.McpClientAutoConfiguration
      - org.springframework.ai.mcp.client.common.autoconfigure.McpToolCallbackAutoConfiguration

    mcp:
      client:
        enabled: true
        streamable-http:
          connections:
            jobda-server:
              url: http://15.164.83.163:8080

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always